services:
  db:
    image: postgres:15
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: myapp
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

  api:
    build: 
      context: .
      dockerfile: DocumentManagementSystem/Dockerfile
    depends_on:
      - db
      - ai-runner
      - rabbitmq
    environment:
      - ConnectionStrings__MainDatabase=Host=db;Port=5432;Database=myapp;Username=user;Password=password
      - ASPNETCORE_URLS=http://+:80
      - ASPNETCORE_ENVIRONMENT=Development
    ports:
      - "8080:80"
  
  webapp:
    build:
      context: ./documentmanagementui
      dockerfile: Dockerfile
    ports:
      - "5173:5173"
    depends_on:
      - api
    command: npm run dev -- --host

  rabbitmq:
    image: rabbitmq:4-management
    container_name: rabbitmq
    ports:
      - 5672:5672
      - 15672:15672
    environment:
      RABBITMQ_DEFAULT_USER: user
      RABBITMQ_DEFAULT_PASS: pass
    volumes:
      - rabbitmq_data:/var/lib/rabbitmq

  ocr:
    build:
      context: ../OCRWorker
      dockerfile: OCRWorker/Dockerfile
    container_name: ocrworker
    depends_on:
      - rabbitmq
    environment:
      RABBITMQ__HOST: rabbitmq
      RABBITMQ__USER: user
      RABBITMQ__PASS: pass

  ai-runner:
    provider:
      type: model
      options:
        model: ai/smollm2

  minio:
    image: minio/minio
    container_name: minio
    environment:
      - MINIO_ROOT_USER=abcd
      - MINIO_ROOT_PASSWORD=abcd2345
      - MINIO_DEFAULT_BUCKETS=buck1
    ports:
      - "9000:9000"
      - "9001:9001"
    volumes:
      - minio_data:/data
  
  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:8.12.0
    environment:
      - discovery.type=single-node
      - xpack.security.enabled=false
    ports:
      - "9200:9200"

  kibana:
    image: docker.elastic.co/kibana/kibana:8.12.0
    environment:
      - ELASTICSEARCH_HOSTS=http://elasticsearch:9200
    ports:
      - "5601:5601"


volumes:
  pgdata:
  rabbitmq_data:
  minio_data:
