services:
  db:
    image: postgres:15
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: myapp
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

  api:
    build: 
      context: .
      dockerfile: DocumentManagementSystem/Dockerfile
    depends_on:
      - db
    environment:
      ConnectionStrings__Default: "Host=db;Database=myapp;Username=user;Password=password"
    expose:
      - "80"
  
  webapp:
    build:
      context: ./documentmanagementui
      dockerfile: Dockerfile
    ports:
      - "8080:80"
    depends_on:
      - api

  rabbitmq:
    image: rabbitmq:4-management
    container_name: rabbitmq
    ports:
      - 5672:5672
      - 15672:15672
    volumes:
      - rabbitmq_data:/var/lib/rabbitmq

volumes:
  pgdata:
  rabbitmq_data:
